general:
steps:
  mtaBuild:
    buildTarget: 'CF'

  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'Dimensys.DEVSUBCF'
      space: 'mjs'
      credentialsId: 'CF_CREDENTIALSID'
